os: linux

language: java
services:
  - docker
cache: bundler
dist: focal

install: skip

jobs:
  include:
    - name: testing
      script: true

after_success:
  - echo passed
  - echo $ACC_TEST_VAR
  - echo $ACC_Unsecret
  - echo $newVar
  - echo $newUnsecretVar
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
